# Generated by Django 6.1.1 on 2026-10-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.CharField(max_length=500, verbose_name='Ссылка на изображение'),
        ),
    ]
