# Generated by Django 6.1.1 on 2026-10-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_galleryimage_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['id'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Наши работы'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Главная'), ('contacts', 'Контакты'), ('gallery', 'Наши работы'), ('feedback', 'Обратная связь'), ('custom', 'Произвольная')], default='custom', max_length=20, verbose_name='Тип страницы'),
        ),
    ]
