# Generated by Django 6.1.1 on 2026-10-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_galleryimage_options_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True, verbose_name='День')),
                ('text', models.CharField(max_length=400, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания планировщика',
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='QueuedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_path', models.CharField(max_length=200, verbose_name='Задача')),
                ('args', models.JSONField(default=list, verbose_name='Аргументы')),
                ('kwargs', models.JSONField(default=dict, verbose_name='Именованные аргументы')),
                ('status', models.CharField(choices=[('READY', 'В очереди'), ('RUNNING', 'Выполняется'), ('FAILED', 'Ошибка'), ('SUCCESSFUL', 'Готово')], default='READY', max_length=20, verbose_name='Статус')),
                ('return_value', models.JSONField(blank=True, null=True, verbose_name='Результат')),
                ('error_class', models.CharField(blank=True, max_length=200, verbose_name='Ошибка')),
                ('error_traceback', models.TextField(blank=True, verbose_name='Трассировка')),
                ('worker_id', models.CharField(blank=True, max_length=64, verbose_name='Воркер')),
                ('enqueued_at', models.DateTimeField(auto_now_add=True, verbose_name='Поставлена')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начата')),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
            ],
            options={
                'verbose_name': 'Задача в очереди',
                'verbose_name_plural': 'Очередь задач',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='club.feedbackmessage', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Уведомление мастеру',
                'verbose_name_plural': 'Уведомления мастеру',
                'ordering': ['-created_at'],
            },
        ),
    ]
