# Generated by Django 6.1.1 on 2026-10-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_dailyreminder_queuedjob_workshopnotice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueuedJob',
        ),
        migrations.DeleteModel(
            name='WorkshopNotice',
        ),
    ]
